export type Tables = {
  account: {
    is_seed_account: boolean,
    email_address: string,
    account_id: number,
    account_notes: string,
    is_application_accepted: boolean,
    password_salt: string,
    password_hash: string,
  },
  age_group: {
    is_child: boolean,
    age_group: string,
  },
  attendee: {
    dietary_restrictions: string,
    name: string | null,
    notes: string,
    discord_handle: string | null,
    interested_in_volunteering: boolean,
    interested_in_pre_call: boolean,
    planning_to_camp: boolean,
    attendee_id: number,
    associated_account_id: number,
    age_group: string | null,
  },
  event: {
    description: string,
    event_id: number,
    location: string | null,
    name: string,
    end: unknown | null,
    start: unknown,
    created_by_account_id: number,
  },
  festival: {
    end_date: unknown,
    festival_site_id: number,
    start_date: unknown,
    festival_id: number,
    available_tickets: number,
    festival_name: string,
  },
  festival_site: {
    festival_site_name: string,
    festival_site_id: number,
    location: unknown,
  },
  invite_code: {
    used_by_account_id: number | null,
    festival_id: number,
    created_by_account_id: number,
    code: string,
    invite_code_id: number,
  },
  next_festival: {
    festival_name: string | null,
    available_tickets: number | null,
    festival_id: number | null,
    end_date: unknown | null,
    festival_site_id: number | null,
    start_date: unknown | null,
  },
  ticket: {
    owned_by_account_id: number | null,
    purchased_on: unknown,
    ticket_type_id: number,
    ticket_id: number,
    assigned_to_attendee_id: number | null,
  },
  ticket_type: {
    ticket_type: string,
    price_in_cents: number,
    festival_id: number,
    ticket_type_id: number,
  },
}

export type TableName = keyof Tables